# Generated by Django 5.2.7 on 2025-10-22 05:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # No dependency on Django's auth user; this project uses a custom unmanaged
    # AppUser model in the 'app' app. Create tables for knowledge independently.
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('visibility', models.CharField(choices=[('private', '仅自己'), ('department', '部门可见'), ('public', '所有人可见')], default='private', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AppUser')),
            ],
            options={
                'db_table': 'knowledge_items',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='knowledge/%Y/%m/%d/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='knowledge.knowledgeitem')),
            ],
            options={
                'db_table': 'knowledge_attachments',
            },
        ),
    ]
