# Generated by Django 5.2.7 on 2025-10-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lead_department',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
