# Generated by Django 5.2.7 on 2025-10-20 03:59

from django.db import migrations, models


def seed_departments(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Department = apps.get_model('projects', 'Department')
    names = (
        Project.objects
        .exclude(lead_department__isnull=True)
        .exclude(lead_department__exact='')
        .values_list('lead_department', flat=True)
        .distinct()
    )
    for name in names:
        normalized = name.strip()
        if not normalized:
            continue
        Department.objects.get_or_create(name=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_lead_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_departments, migrations.RunPython.noop),
    ]
