# Generated by GitHub Copilot on 2025-10-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AppUser',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('username', models.CharField(max_length=64, unique=True)),
                        ('password_hash', models.CharField(max_length=255)),
                        ('display_name', models.CharField(max_length=64)),
                        ('needs_password_reset', models.BooleanField(db_column='needs_password_reset', default=False)),
                    ],
                    options={
                        'db_table': 'app_users',
                        'managed': False,
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('can_manage_projects', models.BooleanField(default=False)),
                ('can_manage_tasks', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_permissions', models.BooleanField(default=False)),
                ('can_view_all_tasks', models.BooleanField(default=False)),
                ('can_edit_all_tasks', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permission_groups',
                'ordering': ['name'],
            },
        ),
    ]
