# Generated by GitHub Copilot on 2025-10-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('projects', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.appuser')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.department')),
                ('permission_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.permissiongroup')),
            ],
            options={
                'db_table': 'user_profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
