# Generated by Django 5.2.7 on 2025-10-20 05:09

import attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_attachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=attachments.models.UnicodeFileSystemStorage(), upload_to='attachments/%Y/%m/%d/'),
        ),
    ]
